{{- $fullName := include "ufc-gateway.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ufc-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.arms.enabled }}
  arms-license-key: {{ .Values.arms.licenseKey }}
  {{- end }}

  mqtt-password: {{ .Values.mqtt.password }}

  # Gateway access key secret
  gateway-access-key-secret: {{ .Values.gateway.accessKeySecret }}
