apiVersion: v1
kind: Service
metadata:
  name: {{ include "ufc-gateway.fullname" . }}
  labels:
    {{- include "ufc-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # see deployment containers[0].ports
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5555
      targetPort: eplat-cmd
      protocol: TCP
      name: eplat-cmd
    - port: 6666
      targetPort: eplat-file
      protocol: TCP
      name: eplat-file
  selector:
    {{- include "ufc-gateway.selectorLabels" . | nindent 4 }}
