apiVersion: v1
kind: Service
metadata:
  name: {{ include "ufc-be.fullname" . }}
  labels:
    {{- include "ufc-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # see deployment containers[0].ports
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ufc-be.selectorLabels" . | nindent 4 }}
