{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ufc-be.serviceAccountName" . }}
  labels:
  {{ include "ufc-be.labels" . | nindent 4 }}
{{- end -}}
